### ISSUE TITLE
No PASS reports with Dancer2 0.159000 and newer

### ISSUE THREAD

**Issue by eserte** [shumphrey/Dancer2-Plugin-ProgressStatus#2]
See
* http://matrix.cpantesters.org/?dist=Dancer2-Plugin-ProgressStatus
* http://analysis.cpantesters.org/solved?distv=Dancer2-Plugin-ProgressStatus-0.016#mod%3ADancer2

**Comment by shumphrey** [comment]
This should be fixed now, with a new release on its way to cpan.
